# YouTube Automation System Configuration - Ubuntu Server Ready
project:
  name: "MonAY - YouTube Automation System (Ubuntu Server)"
  version: "1.0.0"
  environment: "production"

# API Configuration
apis:
  youtube:
    api_key: "${YOUTUBE_API_KEY}"
  
  # Simplified LLM configuration without Hugging Face
  llm:
    model_type: "local"
    provider: "openai_compatible"
    api_base: "http://localhost:11434/v1"  # Ollama or similar local endpoint
    model_name: "llama2"
    max_tokens: 4000
    temperature: 0.7
  
  # Simplified TTS without Hugging Face
  tts:
    engine: "system"
    provider: "local"
    voice: "default"
    speed: 1.0
    enable_voice_cloning: false

# Content Generation Settings
content:
  video_length: 300
  upload_schedule: "daily"
  trending_sources: ["youtube", "reddit"]
  content_types: ["educational", "entertainment", "news", "tutorial"]
  languages: ["en"]
  
  text_generation:
    model: "local"
    max_length: 1000
    num_return_sequences: 1
  
  video_generation:
    model_type: "local"
    resolution: "1920x1080"
    fps: 30
    num_frames: 60
    guidance_scale: 7.5
    num_inference_steps: 50
  
  image_generation:
    model: "local"
    steps: 50
    guidance_scale: 7.5
    resolution: "1920x1080"

# Infrastructure - Ubuntu Server Optimized
infrastructure:
  max_cpu_usage: 80
  max_memory_usage: 85
  storage_limit: "500GB"
  backup_frequency: "daily"
  
  # Relative paths for server compatibility
  model_cache_dir: "./models/cache"
  download_models_on_startup: false  # Manual model management

# WAN Video Generation Configuration
wan:
  mode: "local"  # Use local WAN installation
  api_url: "http://localhost:8000"
  token: "local"
  timeout: 300
  max_retries: 3
  local_path: "./wan"  # Path to local WAN installation
  enable_gpu: true
  model_precision: "fp16"

# Logging - Ubuntu systemd compatible
logging:
  level: "INFO"
  file: "./data/logs/monay_production.log"
  max_size: "100MB"
  backup_count: 5